# haven't completed this :p

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          # ------- below can be used for hpa ------------
          resources:
            requests:
              cpu: "500m"
              # memory: "256mi"
            limits:
              cpu: "1000m"
              # memory: "512mi"
              # ------------------- end --------------------
          ports:
            - containerPort:
